### ISSUE TITLE
[bug] hard coded value of the model option in `mycoai-map`

### ISSUE THREAD

**Issue by CunliangGeng** [MycoAI/MycoAI#3]
No matter what value I provide to `--model` of `mycoai-map`, it gives the following error:

```
$  mycoai-map data/test1.fasta --classification prediction.csv --model ../MycoAI-CNN-HLS.pt

/opt/homebrew/anaconda3/envs/barcoding/lib/python3.10/site-packages/mycoai/utils.py:52: UserWarning: No cuda-enabled GPUs available, using CPU
  warnings.warn('No cuda-enabled GPUs available, using CPU')
wandb: (1) Private W&B dashboard, no account required
wandb: (2) Create a W&B account
wandb: (3) Use an existing W&B account
wandb: (4) Don't visualize my results
wandb: Enter your choice: 4
wandb: You chose "Don't visualize my results"
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/barcoding/bin/mycoai-map", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/anaconda3/envs/barcoding/lib/python3.10/site-packages/mycoai/scripts/map.py", line 99, in main
    map(args.fasta_filepath, args.out[0], args.classification[0],
  File "/opt/homebrew/anaconda3/envs/barcoding/lib/python3.10/site-packages/mycoai/scripts/map.py", line 24, in map
    model = torch.load('models/MycoAI-multi-HLS.pt', map_location=device)
  File "/opt/homebrew/anaconda3/envs/barcoding/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/homebrew/anaconda3/envs/barcoding/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/homebrew/anaconda3/envs/barcoding/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/MycoAI-multi-HLS.pt'
```

**Comment by luukromeijn** [comment]
The issue should be solved now.
